./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
./gamble.bash | grep WINNER
